package com.srijeesolution.rojgaarwaala.network.constant

import retrofit2.http.DELETE

class NetworkConstants {
    companion object {
        const val ON_LOGIN = "login"
        const val ON_REGISTER = "register"
        const val ON_LOGOUT = "logout"
        const val HOMEPAGE_DATA = "home"
        const val GET_PROFILE = "user"
        const val UPDATE_PROFILE = "profile/update"
        const val JOB_SUBMIT = "job/add"
        const val SEND_OTP = "send-otp"
        const val VERIFY_OTP = "verify-otp"
        const val CATEGORIES = "categories"
        const val CATEGORIES_LIST = "category-list"
        const val CITY_LIST = "search/city"
        const val VIDEO_DETAILS = "video/{id}"
        const val JOB_LIST = "job/list"
        const val CATEGORY_VIDEOS = "category/{id}/videos"
        const val TOP_VIDEOS = "top-videos"
        const val VIDEO_LIKE = "video/like"
        const val VIDEO_UNLIKE = "video/unlike"
        const val VIDEO_REMOVE_REACTION = "video/remove-reaction"
        const val VIDEO_INCREMENT_VIEW = "video/increment-view"
        const val JOB_DELETE = "job/delete/{id}"
        const val JOB_UPDATE = "job/update/{id}"
            const val SCHEDULED_IMAGES_GROUPED = "scheduled-images/grouped"
    const val SCHEDULED_IMAGES = "scheduled-images"
    const val SECTION_STORIES_GROUPED = "section-stories/grouped-by-time"
        const val STORIES_ACTIVE = "stories/active"
        const val STORIES_VIEW = "stories/{id}/view"
        const val JOB_APPLICATIONS = "job-applications"
        const val JOB_APPLICATIONS_MY = "job-applications/my"
        const val JOB_APPLICATION_DETAIL = "job-applications/{id}"
        const val JOB_APPLICATION_ORDER = "job-applications/{id}/razorpay-order"
        const val JOB_APPLICATION_CONFIRM = "job-applications/{id}/confirm-payment"
        const val JOB_APPLICATION_FAILED = "job-applications/{id}/payment-failed"
        const val HELP_DESK_CONFIG = "help-desk/config"
        const val HELP_DESK_FAQS = "help-desk/faqs"
        const val HELP_DESK_TUTORIALS = "help-desk/tutorials"
        const val ENQUIRY_SUBMIT = "enquiry/submit"
    }
}